export const quotes = [
	"You don't have a TV? What's all your furniture pointed at?",
	"Welcome to the real world! It sucks. You're gonna love it!",
	"Oh, I wish I could, but I don't want to.",
	'Oh God. Can open. Worms everywhere!',
	"I'm Chandler. I make jokes when I’m uncomfortable.",
	'I tell you, when I actually die, some people are gonna get seriously haunted.',
	"It's a moo point. It’s like a cow's opinion; it doesn't matter. It's moo.",
	"I'm a gym member. I try to go four times a week, but I've missed the last twelve hundred times.",
	'We were on a break!',
	"You hung up on the pizza place? I don't hang up on your friends!",
	"Joey doesn't share food!",
	'Well, the fridge broke, so I had to eat everything.',
	'We are dessert-stealers. We are living outside the law.',
	"Where do you want to go to lunch? Mama's Little Bakery, Chicago, Illinois.",
	'What was I thinking at dinner? "Do you want soup or salad?" Both! Always order both!',
	'You see, my sister makes these amazing turkey sandwiches. Her secret is, she puts an extra slice of gravy-soaked bread in the middle; I call it the Moist Maker.',
	'A promise between friends means never having to give a reason.',
	"You didn't cry when Bambi's mom died? Yes, it was so sad when the guy stopped drawing the deer.",
	'Something is wrong with the left phalange!',
	"Look at me! I'm Chandler! Could I BE wearing any more clothes?",
	'What a small world. Yet I never run into Beyoncé.',
	'You have really great hair. Oh thanks, I grow it myself.',
	'They don’t know that we know they know we know.',
	'I was backpacking through western Europe...',
	'You have to stop the Q-Tip when there’s resistance!',
	"You can't just give up. Is that what a dinosaur would do?",
	'Three bathrooms in this place, and I threw up in a coat closet.',
	"I'm sorry, it was a one-time thing. I was very drunk, and it was someone else's subconscious.",
	"I understand why Superman is here, but why is there a porcupine at the Easter Bunny's funeral?",
	"Santa, the armadillo and I will have a little talk in the kitchen. There's a sentence I never thought I'd say.",
	"What if he calls his own cell phone to find out who found it and I answer and we start talking and we fall in love? I mean, wouldn't that be a great story? Kind of like a fairy tale for the digital age.",
	"Come on, Ross, you're a paleontologist. Dig a little deeper.",
	'That is brand new information!',
	"You know what I figure? If I can do laundry, there's nothing I can’t do.",
	"I just stopped and I said, what if I don't want to be a shoe? What if I want to be a purse, you know, or a hat?",
	'I wanna quit the gym!',
	'We said aloof, not a doof!',
	'Be sleepy! And grumpy! Stop naming dwarves!',
	'We ordered the Joey Special. Three pizzas?!'
];
